SELECT jh.START_DATE, jh.EMPLOYEE_ID,
(SELECT CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME) FROM hr.employees AS e WHERE e.EMPLOYEE_ID = jh.EMPLOYEE_ID)
AS Nome_completo,
jh.JOB_ID,
(SELECT j.JOB_TITLE FROM hr.jobs AS j WHERE j.JOB_ID = jh.JOB_ID) AS Cargo,
jh.DEPARTMENT_ID,
(SELECT d.DEPARTMENT_NAME FROM hr.departments AS d WHERE d.DEPARTMENT_ID = jh.DEPARTMENT_ID) AS Departamento
FROM hr.job_history AS jh
ORDER BY Nome_completo DESC;
